#!/bin/bash
# Paqet Server Installer for Ubuntu
# Usage: curl -sSL <url> | sudo bash
#    or: sudo bash install-paqet-server.sh

set -e

# Configuration
PAQET_PORT="${PAQET_PORT:-9999}"
PAQET_REPO="https://github.com/hanselime/paqet.git"
GO_VERSION="1.23.5"
INSTALL_DIR="/opt/paqet"
CONFIG_DIR="/etc/paqet"
BINARY_PATH="/usr/local/bin/paqet"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Functions for colored output
info() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Check root
[[ $EUID -ne 0 ]] && error "This script must be run as root"

# Detect architecture
ARCH=$(uname -m)
case $ARCH in
    x86_64) GO_ARCH="amd64" ;;
    aarch64) GO_ARCH="arm64" ;;
    *) error "Unsupported architecture: $ARCH" ;;
esac

info "Starting paqet server installation..."

# Step 1: Update system and install packages
info "Updating system packages..."
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -qq

info "Installing required packages..."
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    git curl wget nano vim htop net-tools unzip zip \
    software-properties-common build-essential \
    libpcap-dev iptables-persistent

success "System packages installed"

# Step 2: Configure UFW
info "Configuring firewall..."
if command -v ufw &>/dev/null; then
    ufw allow 443/tcp >/dev/null 2>&1 || true
    ufw allow ${PAQET_PORT}/tcp >/dev/null 2>&1 || true
    success "UFW rules configured"
else
    warn "UFW not found, skipping firewall configuration"
fi

# Step 3: Install Go
info "Installing Go ${GO_VERSION}..."
GO_TAR="go${GO_VERSION}.linux-${GO_ARCH}.tar.gz"
wget -q "https://go.dev/dl/${GO_TAR}" -O /tmp/go.tar.gz
rm -rf /usr/local/go
tar -C /usr/local -xzf /tmp/go.tar.gz
rm /tmp/go.tar.gz
export PATH=/usr/local/go/bin:$PATH
echo 'export PATH=/usr/local/go/bin:$PATH' > /etc/profile.d/go.sh
success "Go $(go version | awk '{print $3}') installed"

# Step 4: Clone and build paqet
info "Cloning paqet repository..."
rm -rf "$INSTALL_DIR"
git clone --depth 1 "$PAQET_REPO" "$INSTALL_DIR" 2>/dev/null
cd "$INSTALL_DIR"

info "Building paqet..."
GIT_COMMIT=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
BUILD_TIME=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
CGO_ENABLED=1 go build -v -a -trimpath \
    -ldflags "-s -w -X 'paqet/cmd/version.GitCommit=${GIT_COMMIT}' -X 'paqet/cmd/version.BuildTime=${BUILD_TIME}'" \
    -o paqet ./cmd/main.go 2>/dev/null

cp paqet "$BINARY_PATH"
chmod +x "$BINARY_PATH"
success "Paqet built and installed to $BINARY_PATH"

# Step 5: Auto-detect network configuration
info "Detecting network configuration..."

# Get default interface
INTERFACE=$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev") print $(i+1)}' | head -1)
[[ -z "$INTERFACE" ]] && error "Could not detect network interface"

# Get server IP
SERVER_IP=$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1)}' | head -1)
[[ -z "$SERVER_IP" ]] && error "Could not detect server IP address"

# Get gateway IP
GATEWAY_IP=$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="via") print $(i+1)}' | head -1)
[[ -z "$GATEWAY_IP" ]] && error "Could not detect gateway IP"

# Get gateway MAC (ping first to populate ARP)
ping -c 1 -W 1 "$GATEWAY_IP" >/dev/null 2>&1 || true
ROUTER_MAC=$(ip neigh show "$GATEWAY_IP" 2>/dev/null | awk '{print $5}' | head -1)
[[ -z "$ROUTER_MAC" || "$ROUTER_MAC" == "FAILED" ]] && error "Could not detect gateway MAC address"

# Generate secret key
SECRET_KEY=$("$BINARY_PATH" secret)

success "Network detected: interface=$INTERFACE, ip=$SERVER_IP, gateway_mac=$ROUTER_MAC"

# Step 6: Create configuration
info "Creating configuration..."
mkdir -p "$CONFIG_DIR"

cat > "${CONFIG_DIR}/server.yaml" << EOF
# Paqet Server Configuration
# Generated by installer on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
role: "server"

log:
  level: "info"

listen:
  addr: ":${PAQET_PORT}"

network:
  interface: "${INTERFACE}"
  ipv4:
    addr: "${SERVER_IP}:${PAQET_PORT}"
    router_mac: "${ROUTER_MAC}"
  tcp:
    local_flag: ["PA"]

transport:
  protocol: "kcp"
  conn: 1
  kcp:
    mode: "fast"
    key: "${SECRET_KEY}"
    block: "aes"
EOF

success "Configuration created at ${CONFIG_DIR}/server.yaml"

# Step 7: Configure iptables
info "Configuring iptables rules..."
# Use -I (Insert) to ensure these rules come first
iptables -t raw -C PREROUTING -p tcp --dport ${PAQET_PORT} -j NOTRACK 2>/dev/null || \
    iptables -t raw -I PREROUTING -p tcp --dport ${PAQET_PORT} -j NOTRACK
iptables -t raw -C OUTPUT -p tcp --sport ${PAQET_PORT} -j NOTRACK 2>/dev/null || \
    iptables -t raw -I OUTPUT -p tcp --sport ${PAQET_PORT} -j NOTRACK
iptables -t mangle -C OUTPUT -p tcp --sport ${PAQET_PORT} --tcp-flags RST RST -j DROP 2>/dev/null || \
    iptables -t mangle -I OUTPUT -p tcp --sport ${PAQET_PORT} --tcp-flags RST RST -j DROP

# Save iptables rules
netfilter-persistent save >/dev/null 2>&1 || iptables-save > /etc/iptables/rules.v4
success "Iptables rules configured and saved"

# Step 8: Create systemd service
info "Creating systemd service..."
cat > /etc/systemd/system/paqet.service << 'EOF'
[Unit]
Description=Paqet Packet-level Proxy Server
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/paqet run -c /etc/paqet/server.yaml
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable paqet >/dev/null 2>&1
systemctl start paqet
success "Systemd service created and started"

# Step 9: Verify service is running
sleep 2
if systemctl is-active --quiet paqet; then
    success "Paqet server is running!"
else
    error "Paqet service failed to start. Check: journalctl -u paqet"
fi

# Step 10: Output client configuration
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}           PAQET SERVER INSTALLATION COMPLETE                  ${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${YELLOW}CLIENT CONFIGURATION PARAMETERS:${NC}"
echo ""
echo "  Server Address:    ${SERVER_IP}:${PAQET_PORT}"
echo "  Secret Key:        ${SECRET_KEY}"
echo "  Block Cipher:      aes"
echo "  KCP Mode:          fast"
echo "  Transport:         kcp"
echo ""
echo -e "${YELLOW}EXAMPLE CLIENT CONFIG (client.yaml):${NC}"
echo ""
cat << CLIENTEOF
role: "client"

log:
  level: "info"

socks5:
  - listen: "127.0.0.1:1080"

network:
  interface: "<YOUR_INTERFACE>"        # Your local network interface
  ipv4:
    addr: "<YOUR_LOCAL_IP>:0"          # Your local IP (port 0 = auto)
    router_mac: "<YOUR_ROUTER_MAC>"    # Your gateway MAC address
  tcp:
    local_flag: ["PA"]
    remote_flag: ["PA"]

server:
  addr: "${SERVER_IP}:${PAQET_PORT}"

transport:
  protocol: "kcp"
  conn: 1
  kcp:
    mode: "fast"
    key: "${SECRET_KEY}"
    block: "aes"
CLIENTEOF

echo ""
echo -e "${YELLOW}USEFUL COMMANDS:${NC}"
echo "  Check status:      systemctl status paqet"
echo "  View logs:         journalctl -u paqet -f"
echo "  Restart service:   systemctl restart paqet"
echo "  Stop service:      systemctl stop paqet"
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
